name: jobmanagement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.3.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  icons_plus: ^5.0.0
  intl: ^0.20.2
  flutter_slidable: ^4.0.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
