name: financial_analyzer
description: A cross-platform financial analysis Flutter application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # UI & Animations
  flutter_animate: ^4.2.0+1
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1

  # HTTP & API
  dio: ^5.4.0
  json_annotation: ^4.8.1
  file_selector: ^1.0.3
  permission_handler: ^11.3.0
  url_launcher: ^6.3.0
  pdf: ^3.10.8
  open_file: ^3.3.2

  # Storage & Persistence
  shared_preferences: ^2.2.2

  # File Operations (remove file_picker for now to avoid Windows issues)
  path_provider: ^2.1.2

  # Utils
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  logger: ^2.0.2+1
  intl: ^0.19.0
  go_router: ^12.1.3

  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
