name: calley
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  chewie: ^1.12.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  http: ^1.4.0
  pie_chart: ^5.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
